package fa.group4.MockProject.entity;

public class productdetailtablet {
	private String productID;
	private String screenTechnology;
	private int resolution;
	private int screenSize;
	private String productDetailTablet;
	private String operatingSystem;
	private String cpu;
	private String cpuSpeed;
	private String gpu;
	private int ram;
	private int rom;
	private int romAvailable;
	private String externalMemoryCard;
	private String rearCameraResolution;
	private String movie;
	private String featureRearCamera;
	private String frontCameraResolution;
	private String mobileNetworkSupport;
	private String sim;
	private boolean canCall;
	private String wifi;
	private String gps;
	private String bluetooth;
	private String chargePort;
	private String headphonePort;
	private String otherPort;
	private boolean record;
	private boolean radio;
	private int battery;
	private String batteryType;
	private int maxChargeSupport;
	private String material;
	private float length;
	private float width;
	private float weight;
	private String releaseTime;
}
